### ISSUE TITLE
Assembly Definition json files in Unity 2019.x.x breaks the building of the demos

### ISSUE THREAD

**Issue by Maesla** [modesttree/Zenject#135]
**Describe the bug**
Running Playmode Tests in a test build doesn't work. It results in a compiling error, and the project gets corrupted. You have to reimport all to get the project right again

**To Reproduce**
Checkout the Extenject Project at commit cb40f53d3e1e99a022968bed7e9f4152cc52080a and Open with the Unity Version 2019.1.0f2 (I have tried with 2019.3.6f1 and the result is the same)

Click in Run All In Player
![imagen](https://user-images.githubusercontent.com/25863696/82531239-3e60d600-9b3f-11ea-8cdc-dcd294d7d901.png)
 See the console
![imagen](https://user-images.githubusercontent.com/25863696/82531275-53d60000-9b3f-11ea-8e67-2e8c0188217a.png)

**Expected behavior**
A test build is created and all the playmode test passes

**Screenshots**

**Extenject and Unity info (please complete the following information):**
 - Zenject version:9.1.0
 - Unity version:2019.1.0f2
 - Project's scripting backend [e.g. Mono/IL2CPP] Mono

**Additional context**

**Comment by Mathijs-Bakker** [comment]
Yes, confirmed!
Unity changed the assembly definitions in 2019.1.0. And in newer updates some more.
Referencing the Zenject.dll is now mandatory with the references keyword.  Or by simply adding the dll in the inspector of the current .asmdef.

Same goes for the supplied tests.

This should and must be addressed properly. I don't know if the demos lose backwards compatibility with Unity 2018.LTS.

Thank you for notifying!

**Comment by Mathijs-Bakker** [comment]
Fixed and pushed into master.

**Comment by Maesla** [comment]
Hello, 

I have tested the last commit (c2e33500a84f9408a809deca2af2c55494ab2482), and it has the same problem still.

May I be missing something?

Thank you

![imagen](https://user-images.githubusercontent.com/25863696/82802729-a5ec8d80-9e7f-11ea-9236-3c8c05076389.png)

**Comment by Mathijs-Bakker** [comment]
Unity changed the use of assembly definitions in 2019.1.
And in 2019.3 they decided to do some more changes.

I have updated Extenject for the unity 2019.1 on the [Unity2019.1.0 branch](https://github.com/svermeulen/Extenject/tree/Unity2019.1.0).
And for Unity 2019.3++ you can use the master branch.

Unity 2019.2 has not been tested.

**Comment by Maesla** [comment]
Yes, I understand, but it still doesn't work for me, maybe there is something that needs to be manually updated

I am using 
Unity 2019.3.0f6
Master branch, last commit c2e33500a84f9408a809deca2af2c55494ab2482
The Extenject own project (not mine)
I have reimported all, just in case
Clicking **Running all in player** doesn't work for me.
See the gif below
![run all in player](https://user-images.githubusercontent.com/25863696/82821789-fb876100-9ea4-11ea-8af1-ad6c92888aa3.gif)

Thank you

**Comment by Mathijs-Bakker** [comment]
~~For probing reasons...
Could you remove **Assets/SampleBuilder** directory? 
And see what happens?~~

Could you install and test the [release candidate](https://github.com/svermeulen/Extenject/tree/release-candidate) for me?
The BuildDemo has been received an update yesterday. And has not been tested on Windows.

**Comment by Maesla** [comment]
Yes, sure.

Checking out release candidate branch,
Edit Mode tests: all passes
Play Mode tests: all passes
Run all in player (StandaloneWindows64): Player build failed

Same behaviour

**Comment by NoTuxNoBux** [comment]
I'm (still) experiencing the same issue in Unity 2019.4.16f; Extenject itself can be found just fine, but the classes from the TestFramework optional extras, such as `ZenjectIntegrationTestFixture`, cannot be found no matter what I try.

My assemby definition correctly references `Zenject-TestFramework` in the `references` section, which is the assembly definition shipped with the files in `Library\PackageCache\com.svermeulen.extenject@VERSION\OptionalExtras\TestFramework`, but these classes are still not being found.

I was able to work around the issue for now by copying the optional extras into my tests folder for now, in case that helps anyone.

EDIT: I can create a new ticket if this is another issue altogether (alternatively this one could be reopened).
